# Collocation

In [1]:
import polars as pl
import polars.selectors as cs
import polars_corpus as plc
import math

In [2]:
bnc = pl.read_parquet("bnc.parquet")

In [3]:
m = plc.search(bnc, '[token="dangerous"]')

In [4]:
collocs = m.collocates("token", window=3).sort(by="f12", descending=True)
collocs

shape: (625, 5)
┌───────────┬──────┬───────┬─────────┬───────────┐
│ collocate ┆ f12  ┆ f1    ┆ f2      ┆ n         │
│ ---       ┆ ---  ┆ ---   ┆ ---     ┆ ---       │
│ str       ┆ u32  ┆ i32   ┆ u32     ┆ i32       │
╞═══════════╪══════╪═══════╪═════════╪═══════════╡
│ .         ┆ 1760 ┆ 32676 ┆ 4715138 ┆ 112429158 │
│ ,         ┆ 1501 ┆ 32676 ┆ 5017057 ┆ 112429158 │
│ and       ┆ 1230 ┆ 32676 ┆ 2506072 ┆ 112429158 │
│ a         ┆ 1115 ┆ 32676 ┆ 2036673 ┆ 112429158 │
│ the       ┆ 1088 ┆ 32676 ┆ 5405646 ┆ 112429158 │
│ …         ┆ …    ┆ …     ┆ …       ┆ …         │
│ black     ┆ 5    ┆ 32676 ┆ 19147   ┆ 112429158 │
│ belonging ┆ 5    ┆ 32676 ┆ 1371    ┆ 112429158 │
│ move      ┆ 5    ┆ 32676 ┆ 19246   ┆ 112429158 │
│ during    ┆ 5    ┆ 32676 ┆ 36114   ┆ 112429158 │
│ food      ┆ 5    ┆ 32676 ┆ 16528   ┆ 112429158 │
└───────────┴──────┴───────┴─────────┴───────────┘

In [5]:
ll = collocs.with_columns(LL=plc.loglik("f12", "f1", "f2", "n")).sort(by="LL", descending=True).head(20)
ll

shape: (20, 6)
┌─────────────┬──────┬───────┬─────────┬───────────┬────────────┐
│ collocate   ┆ f12  ┆ f1    ┆ f2      ┆ n         ┆ LL         │
│ ---         ┆ ---  ┆ ---   ┆ ---     ┆ ---       ┆ ---        │
│ str         ┆ u32  ┆ i32   ┆ u32     ┆ i32       ┆ f64        │
╞═════════════╪══════╪═══════╪═════════╪═══════════╪════════════╡
│ potentially ┆ 154  ┆ 32676 ┆ 2373    ┆ 112429158 ┆ 1370.04015 │
│ most        ┆ 261  ┆ 32676 ┆ 87690   ┆ 112429158 ┆ 745.686673 │
│ very        ┆ 285  ┆ 32676 ┆ 114997  ┆ 112429158 ┆ 721.001424 │
│ be          ┆ 616  ┆ 32676 ┆ 647322  ┆ 112429158 ┆ 611.472485 │
│ is          ┆ 757  ┆ 32676 ┆ 971795  ┆ 112429158 ┆ 550.752081 │
│ …           ┆ …    ┆ …     ┆ …       ┆ …         ┆ …          │
│ precedent   ┆ 28   ┆ 32676 ┆ 705     ┆ 112429158 ┆ 220.921203 │
│ are         ┆ 321  ┆ 32676 ┆ 454599  ┆ 112429158 ┆ 193.331588 │
│ situation   ┆ 58   ┆ 32676 ┆ 15625   ┆ 112429158 ┆ 188.834475 │
│ the         ┆ 1088 ┆ 32676 ┆ 5405646 ┆ 112429158 ┆ 174.157016 │
│ chemicals   ┆ 26   ┆ 32676 ┆ 1822    ┆ 112429158 ┆ 151.916679 │
└─────────────┴──────┴───────┴─────────┴───────────┴────────────┘

In [6]:
# double checking LL for 'potentially dangerous'

# a = frequency of node-collocate pairs
a = 154
# b = frequency of node without collocate
b = 32676-a
# c = frequency of collocate without node
c = 2373-a

# d = words in corpus - occurrences of node and collocate
N = 112429158
d = N - a - b - c

LL2 = 2*(
          a*math.log(a)
         +b*math.log(b)
         +c*math.log(c)
         +d*math.log(d)
         -(a+b)*math.log(a+b)
         -(a+c)*math.log(a+c)
         -(b+d)*math.log(b+d)
         -(c+d)*math.log(c+d)
         +(N)*math.log(N))
LL2

1370.0401501655579